/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ATOMIC_OP_NEEDS_MEMORY_BARRIER 1

#define CAIRO_NO_MUTEX 1

#define HAS_PIXMAN_GLYPHS 1

#define HAVE_MKDIR 0

#undef HAVE_STRNDUP

#define SIZEOF_INT -1

#define SIZEOF_LONG -1

#define SIZEOF_LONG_LONG -1

#define SIZEOF_SIZE_T -1

#define SIZEOF_VOID_P -1

#define WARN_UNUSED_RESULT 

