[versions]
androidMinSdk = "21"
androidTargetSdk = "34"
androidCompileSdk = "34"

jvmTarget = "17"
compose-compiler = "1.5.15"

libVersion = "2.6.4"

composeColorfulSliders = "1.2.2"
paletteKtx = "1.0.0"
composeVersion = "1.7.1"
materialIconsExtended = "1.7.1"

detekt = "1.23.7"
detektCompose = "0.4.12"

kotlin = "1.9.25"
agp = "8.6.1"

coroutines = "1.9.0"
appCompat = "1.7.0"
androidxCore = "1.13.1"
androidxLifecycle = "2.8.5"
desugaring = "2.1.2"
composeBom = "2024.09.01"
material3 = "1.3.0"
ksp = "1.9.25-1.0.20"
coil = "2.7.0"
materialKolor = "1.7.0"

activityCompose = "1.9.2"
androidAnimation = "3.0.1"
vectordrawableAnimated = "1.2.0"
androidTiffbitmapfactory = "0.9.9.1"

[libraries]
android-tiffbitmapfactory = { module = "io.github.beyka:Android-TiffBitmapFactory", version.ref = "androidTiffbitmapfactory" }

androidx-vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectordrawableAnimated" }
animation-awebp = { module = "com.github.penfeizhou.android.animation:awebp", version.ref = "androidAnimation" }
animation-awebp-encoder = { module = "com.github.penfeizhou.android.animation:awebpencoder", version.ref = "androidAnimation" }
animation-avif = { module = "com.github.penfeizhou.android.animation:avif", version.ref = "androidAnimation" }

androidx-material3-window-sizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "composeVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }

materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "composeVersion" }
compose-colorful-sliders = { module = "com.github.SmartToolFactory:Compose-Colorful-Sliders", version.ref = "composeColorfulSliders" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
viewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-animation-core = { module = "androidx.compose.animation:animation-core", version.ref = "composeVersion" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
image-toolbox-library = { id = "image.toolbox.library", version = "unspecified" }
image-toolbox-compose = { id = "image.toolbox.compose", version = "unspecified" }
image-toolbox-maven = { id = "image.toolbox.maven", version = "unspecified" }
